# Generated by Django 5.0.6 on 2026-05-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('type_rapport', models.CharField(choices=[('bilan_carbone', 'Bilan Carbone'), ('esg', 'Rapport ESG'), ('operations', 'Synthèse opérationnelle')], max_length=20)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('genere_par', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rapport BI',
                'ordering': ['-created_at'],
            },
        ),
    ]
