# Generated by Django 5.0.6 on 2026-05-06 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI Permanent'), ('journalier', 'Journalier'), ('moo', 'MOO'), ('stagiaire', 'Stagiaire')], max_length=20)),
                ('poste', models.CharField(blank=True, max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('conge', 'En congé')], default='actif', max_length=20)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('salaire_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taux_journalier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Employé',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='PresenceJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('heures_travaillees', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('montant_du', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('projet_ref', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Présence journalière',
                'ordering': ['-date'],
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
