# Generated by Django 5.0.6 on 2026-05-17 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_affectationtache_realisationtache_tacheprojet_and_more'),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencejournaliere',
            name='paye_le',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MissionMoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_forfaitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paye_le', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('employe', models.ForeignKey(limit_choices_to={'type_contrat': 'moo'}, on_delete=django.db.models.deletion.PROTECT, related_name='missions_moo', to='rh.employe')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_moo', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Mission MOO',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mois', models.DateField(help_text='1er jour du mois concerné (ex: 2026-05-01)')),
                ('brut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('genere', 'Généré'), ('paye', 'Payé')], default='genere', max_length=20)),
                ('paye_le', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'ordering': ['-mois', 'employe__nom'],
                'unique_together': {('employe', 'mois')},
            },
        ),
    ]
