# Generated by Django 5.0.6 on 2026-05-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('rh', '0002_presencejournaliere_paye_le_missionmoo_bulletinpaie'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencejournaliere',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences', to='operations.site'),
        ),
    ]
