# Generated by Django 5.0.6 on 2026-05-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_presencejournaliere_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('technique', 'Technique BTP'), ('agricole', 'Agricole / pépinière'), ('conduite_engin', "Conduite d'engin"), ('management', 'Management'), ('administratif', 'Administratif'), ('autre', 'Autre')], default='technique', max_length=20)),
                ('niveau_max', models.PositiveSmallIntegerField(default=5)),
                ('actif', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Compétence',
                'ordering': ['categorie', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=200)),
                ('organisme', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('date_obtention', models.DateField()),
                ('date_expiration', models.DateField(blank=True, help_text='Vide = sans expiration.', null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Certification',
                'ordering': ['-date_obtention'],
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_conge', models.CharField(choices=[('conges_payes', 'Congés payés'), ('maladie', 'Maladie'), ('maternite', 'Maternité / paternité'), ('sans_solde', 'Sans solde'), ('special', 'Spécial (mariage, deuil…)')], default='conges_payes', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=300)),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='demande', max_length=20)),
                ('approuve_par', models.CharField(blank=True, max_length=200)),
                ('approuve_le', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Congé',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI Permanent'), ('journalier', 'Journalier'), ('moo', 'MOO'), ('stagiaire', 'Stagiaire')], max_length=20)),
                ('poste', models.CharField(blank=True, max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text='Vide = contrat en cours.', null=True)),
                ('salaire_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taux_journalier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motif_fin', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_contrats', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Historique contrat',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niveau', models.PositiveSmallIntegerField(default=1)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acquisitions', to='rh.competence')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Compétence employé',
                'ordering': ['competence__libelle'],
                'unique_together': {('employe', 'competence')},
            },
        ),
    ]
