# Generated by Django 5.0.6 on 2026-05-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_seed_centres_cout'),
        ('projets', '0004_map_centre_cout'),
        ('rh', '0002_presencejournaliere_paye_le_missionmoo_bulletinpaie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_site', models.CharField(choices=[('chantier', 'Chantier BTP'), ('parcelle', 'Parcelle agricole'), ('pepiniere', 'Pépinière'), ('espace_vert', 'Espace vert'), ('depot', 'Dépôt / parc engins'), ('autre', 'Autre')], default='chantier', max_length=20)),
                ('localisation', models.CharField(blank=True, max_length=300)),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='projets.projet')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_geres', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Site',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TacheCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('type_objectif', models.CharField(choices=[('surface', 'Surface (m²)'), ('volume', 'Volume (m³)'), ('unite', 'Unité'), ('lineaire', 'Linéaire (m)'), ('forfait', 'Forfait')], default='unite', max_length=20)),
                ('unite_label', models.CharField(blank=True, help_text='Ex: m², sacs, ml', max_length=50)),
                ('tarif_reference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_catalogue', to='core.centrecout')),
            ],
            options={
                'verbose_name': 'Tâche de catalogue',
                'verbose_name_plural': 'Tâches de catalogue',
                'ordering': ['code'],
            },
        ),
    ]
