# Generated by Django 5.0.6 on 2026-05-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_doc', models.CharField(blank=True, max_length=20, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('type_doc', models.CharField(choices=[('permis', 'Permis'), ('medical', 'Visite médicale'), ('assurance', 'Assurance'), ('certification', 'Certification'), ('env_permit', 'Autorisation environnementale'), ('cnps', 'CNPS / DGI'), ('contrat', 'Contrat'), ('autre', 'Autre')], max_length=20)),
                ('entite_type', models.CharField(blank=True, choices=[('site', 'Chantier / Site'), ('employe', 'Employé'), ('engin', 'Engin / Véhicule'), ('projet', 'Projet'), ('client', 'Client'), ('entreprise', 'Entreprise')], max_length=20)),
                ('entite_id', models.CharField(blank=True, max_length=40)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('fichier_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_expiration', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='entrepriseconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
