# Generated by Django 5.0.6 on 2026-05-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_alter_entrepriseconfig_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreCout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('couleur', models.CharField(default='#386641', help_text='Couleur hex pour les graphes de ventilation', max_length=7)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Centre de coût',
                'verbose_name_plural': 'Centres de coût',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
