# Generated by Django 5.0.6 on 2026-05-23 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_contrat_opportunite'),
        ('operations', '0001_initial'),
        ('projets', '0005_realisationtache_site_tacheprojet_tache_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_engin', models.CharField(choices=[('pelleteuse', 'Pelleteuse'), ('compacteur', 'Compacteur'), ('tractopelle', 'Tractopelle'), ('chargeuse', 'Chargeuse'), ('niveleuse', 'Niveleuse'), ('camion_benne', 'Camion benne'), ('betonniere', 'Bétonnière'), ('tracteur', 'Tracteur'), ('groupe_electro', 'Groupe électrogène'), ('autre', 'Autre')], max_length=20)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('immatriculation', models.CharField(blank=True, max_length=30)),
                ('numero_serie', models.CharField(blank=True, max_length=80)),
                ('annee_mise_service', models.PositiveIntegerField(blank=True, null=True)),
                ('heures_compteur', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('heures_revision', models.DecimalField(decimal_places=1, default=500, help_text='Seuil compteur à partir duquel une révision préventive est due.', max_digits=10)),
                ('duree_vie_estimee_h', models.DecimalField(decimal_places=0, default=10000, help_text="Durée de vie estimée en heures pour calculer l'usure.", max_digits=10)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tarif_location_jour', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_chantier', 'En chantier'), ('en_location', 'En location'), ('en_maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='disponible', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('site_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engins', to='operations.site')),
            ],
            options={
                'verbose_name': 'Engin',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ContratLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('tarif_jour', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, help_text='Renseigné pour une location externe.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations_engin', to='crm.client')),
                ('projet', models.ForeignKey(blank=True, help_text='Renseigné pour une affectation interne.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_engin', to='projets.projet')),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='parc.engin')),
            ],
            options={
                'verbose_name': 'Contrat de location',
                'ordering': ['-date_debut', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_maintenance', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective'), ('revision', 'Révision périodique')], default='preventive', max_length=20)),
                ('date_intervention', models.DateField()),
                ('heures_compteur_intervention', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('description', models.CharField(max_length=300)),
                ('prochaine_revision_heures', models.DecimalField(blank=True, decimal_places=1, help_text="Si renseigné, met à jour le seuil de prochaine révision sur l'engin.", max_digits=10, null=True)),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effectue_par', models.CharField(blank=True, help_text='Atelier interne ou prestataire', max_length=200)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='parc.engin')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'ordering': ['-date_intervention'],
            },
        ),
    ]
