# Generated by Django 5.0.6 on 2026-05-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('intrant', 'Intrant agricole'), ('materiau', 'Matériau BTP'), ('equipement', 'Équipement'), ('consommable', 'Consommable'), ('piece', 'Pièce détachée')], max_length=20)),
                ('unite', models.CharField(choices=[('kg', 'Kilogramme'), ('l', 'Litre'), ('m', 'Mètre'), ('m2', 'Mètre carré'), ('m3', 'Mètre cube'), ('u', 'Unité'), ('sac', 'Sac'), ('tonne', 'Tonne')], default='u', max_length=10)),
                ('stock_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seuil_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stocks.article')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
