# Generated by Django 5.0.6 on 2026-05-23 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('projets', '0005_realisationtache_site_tacheprojet_tache_catalogue'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dechet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_dechet', models.CharField(choices=[('organique', 'Déchet organique / vert'), ('plastique', 'Plastique / emballage'), ('gravats', 'Béton & gravats'), ('metal', 'Métal / ferraille'), ('huile', 'Huile usée / hydrocarbure'), ('bois', 'Bois & palettes'), ('autre', 'Autre')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite', models.CharField(choices=[('kg', 'Kilogramme'), ('tonne', 'Tonne'), ('m3', 'Mètre cube'), ('sac', 'Sac'), ('u', 'Unité')], default='kg', max_length=10)),
                ('date', models.DateField()),
                ('mode_traitement', models.CharField(choices=[('compost', 'Compostage'), ('recyclage', 'Recyclage'), ('reutilisation', 'Réutilisation'), ('valorisation', 'Valorisation énergétique'), ('decharge', 'Mise en décharge'), ('autre', 'Autre')], default='decharge', max_length=20)),
                ('est_valorise', models.BooleanField(default=False, help_text='True si recyclage / réutilisation / valorisation / compostage.')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('origine_projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dechets', to='projets.projet')),
                ('origine_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dechets', to='operations.site')),
            ],
            options={
                'verbose_name': 'Déchet',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LotBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('espece', models.CharField(help_text='Ex: Anacardier, Hévéa, Tomate', max_length=120)),
                ('date_semis', models.DateField()),
                ('date_repiquage', models.DateField(blank=True, null=True)),
                ('quantite_initiale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_actuelle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat_sante', models.CharField(choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('critique', 'Critique'), ('perdu', 'Perdu')], default='bon', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('article', models.ForeignKey(help_text='Intrant / variété concerné.', on_delete=django.db.models.deletion.PROTECT, related_name='lots_biologiques', to='stocks.article')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_biologiques', to='operations.site')),
            ],
            options={
                'verbose_name': 'Lot biologique',
                'ordering': ['-date_semis'],
            },
        ),
        migrations.CreateModel(
            name='TraceurRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_uid', models.CharField(help_text='UID du tag RFID/NFC', max_length=64, unique=True)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('statut', models.CharField(choices=[('en_stock', 'En stock'), ('sorti', 'Sorti / sur site'), ('perdu', 'Perdu / volé'), ('retire', 'Retiré du service')], default='en_stock', max_length=20)),
                ('date_pose', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('article', models.ForeignKey(limit_choices_to={'categorie__in': ['materiau', 'equipement']}, on_delete=django.db.models.deletion.PROTECT, related_name='traceurs_rfid', to='stocks.article')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traceurs_rfid', to='operations.site')),
            ],
            options={
                'verbose_name': 'Traceur RFID',
                'ordering': ['tag_uid'],
            },
        ),
    ]
