# Generated by Django 5.0.6 on 2026-05-21 22:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_seed_centres_cout'),
        ('projets', '0004_map_centre_cout'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120)),
                ('banque', models.CharField(blank=True, max_length=120)),
                ('numero_compte', models.CharField(blank=True, max_length=60)),
                ('type_compte', models.CharField(choices=[('banque', 'Compte bancaire'), ('caisse', 'Caisse'), ('mobile_money', 'Mobile Money')], default='banque', max_length=15)),
                ('solde_initial', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compte de trésorerie',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('ncc', models.CharField(blank=True, max_length=50, verbose_name='N° Compte Contribuable')),
                ('categorie', models.CharField(choices=[('materiaux', 'Matériaux & fournitures'), ('materiel', 'Matériel & équipement'), ('sous_traitance', 'Sous-traitance'), ('services', 'Services'), ('transport', 'Transport & carburant'), ('autre', 'Autre')], default='materiaux', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('localite', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FactureAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('reference', models.CharField(blank=True, help_text='N° de pièce du fournisseur', max_length=100)),
                ('libelle', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('18'), max_digits=5)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=15)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('centre_cout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_achat', to='core.centrecout')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_achat', to='projets.projet')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_achat', to='achats.fournisseur')),
            ],
            options={
                'verbose_name': "Facture d'achat",
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MouvementTresorerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('sens', models.CharField(choices=[('entree', 'Encaissement'), ('sortie', 'Décaissement')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('categorie', models.CharField(choices=[('vente', 'Vente / client'), ('achat', 'Achat / fournisseur'), ('salaire', 'Salaires & paie'), ('charge', 'Charge / frais'), ('impot', 'Impôts & taxes'), ('transfert', 'Transfert interne'), ('autre', 'Autre')], default='autre', max_length=15)),
                ('libelle', models.CharField(max_length=300)),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('mobile', 'Mobile Money')], default='virement', max_length=15)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('centre_cout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_tresorerie', to='core.centrecout')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='achats.comptebancaire')),
                ('facture_achat', models.ForeignKey(blank=True, help_text="Facture d'achat réglée par ce décaissement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decaissements', to='achats.factureachat')),
            ],
            options={
                'verbose_name': 'Mouvement de trésorerie',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
