# Generated by Django 5.0.6 on 2026-05-06 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_client', models.CharField(choices=[('client', 'Client'), ('prospect', 'Prospect'), ('partenaire', 'Partenaire')], default='prospect', max_length=20)),
                ('secteur', models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('btp', 'BTP'), ('collectivite', 'Collectivité'), ('prive', 'Privé')], max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('negociation', 'En négociation')], default='actif', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('localite', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('date_premier_contact', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('objet', models.CharField(max_length=300)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('expire', 'Expiré')], default='brouillon', max_length=20)),
                ('date_emission', models.DateField()),
                ('date_validite', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='crm.client')),
            ],
            options={
                'verbose_name': 'Devis',
                'ordering': ['-date_emission'],
            },
        ),
    ]
