# Generated by Django 5.0.6 on 2026-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ncc',
            field=models.CharField(blank=True, help_text='NCC du client — requis pour la facturation FNE B2B/B2G', max_length=50, verbose_name='N° Compte Contribuable'),
        ),
    ]
