# Generated by Django 5.0.6 on 2026-05-21 23:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_centres_cout'),
        ('crm', '0002_client_ncc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('objet', models.CharField(max_length=300)),
                ('type_contrat', models.CharField(choices=[('prestation', 'Prestation de services'), ('location', 'Location'), ('maintenance', 'Maintenance / Entretien'), ('cadre', 'Contrat-cadre'), ('autre', 'Autre')], default='prestation', max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('reconduction_tacite', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('expire', 'Expiré'), ('resilie', 'Résilié')], default='brouillon', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('centre_cout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='core.centrecout')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='crm.client')),
            ],
            options={
                'verbose_name': 'Contrat',
                'ordering': ['-date_debut', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('phase', models.CharField(choices=[('prospection', 'Prospection'), ('qualification', 'Qualification'), ('proposition', 'Proposition'), ('negociation', 'Négociation'), ('gagnee', 'Gagnée'), ('perdue', 'Perdue')], default='prospection', max_length=15)),
                ('probabilite', models.PositiveSmallIntegerField(default=10, help_text='0 à 100 %')),
                ('valeur_estimee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('date_cloture_prevue', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('centre_cout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunites', to='core.centrecout')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunites', to='crm.client')),
            ],
            options={
                'verbose_name': 'Opportunité',
                'ordering': ['-created_at'],
            },
        ),
    ]
