# Generated by Django 5.0.6 on 2026-05-07 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_affectation', models.DateField()),
                ('objectif_individuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_taches', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Affectation tâche',
            },
        ),
        migrations.CreateModel(
            name='RealisationTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('quantite_realisee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_calcule', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='projets.affectationtache')),
            ],
            options={
                'verbose_name': 'Réalisation tâche',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TacheProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type_objectif', models.CharField(choices=[('surface', 'Surface (m²)'), ('volume', 'Volume (m³)'), ('unite', 'Unité'), ('lineaire', 'Linéaire (m)'), ('forfait', 'Forfait')], default='unite', max_length=20)),
                ('unite_label', models.CharField(blank=True, help_text='Ex: m², sacs, ml', max_length=50)),
                ('objectif_cible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarif_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus_objectif_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='a_faire', max_length=20)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Tâche projet',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='affectationtache',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='projets.tacheprojet'),
        ),
        migrations.AlterUniqueTogether(
            name='affectationtache',
            unique_together={('tache', 'employe', 'date_affectation')},
        ),
    ]
