# Generated by Django 5.0.6 on 2026-05-21 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_centres_cout'),
        ('projets', '0002_affectationtache_realisationtache_tacheprojet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='centre_cout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='core.centrecout'),
        ),
    ]
