# Generated by Django 5.0.6 on 2026-05-17 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_affectationtache_realisationtache_tacheprojet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='chantiers/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='chantiers/%Y/%m/thumb/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('prise_le', models.DateTimeField()),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('type_photo', models.CharField(choices=[('avant', 'Avant chantier'), ('apres', 'Après chantier'), ('incident', 'Incident'), ('autre', 'Autre')], default='autre', max_length=15)),
                ('prise_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos_chantier', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Photo chantier',
                'ordering': ['-prise_le'],
            },
        ),
    ]
