# Generated by Django 5.0.6 on 2026-05-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('projets', '0004_map_centre_cout'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisationtache',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realisations', to='operations.site'),
        ),
        migrations.AddField(
            model_name='tacheprojet',
            name='tache_catalogue',
            field=models.ForeignKey(blank=True, help_text='Modèle de tâche du référentiel — prérenseigne type/unité/tarif.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_projet', to='operations.tachecatalogue'),
        ),
    ]
