# Generated by Django 5.0.6 on 2026-05-06 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=300)),
                ('categorie', models.CharField(choices=[('salaire', 'Salaires & charges sociales'), ('materiel', 'Matériel & équipement'), ('carburant', 'Carburant & transport'), ('sous_traitance', 'Sous-traitance'), ('location', 'Location engins'), ('fourniture', 'Fournitures'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Charge',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée'), ('en_retard', 'En retard'), ('annulee', 'Annulée')], default='brouillon', max_length=25)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField()),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='crm.client')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Facture',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('mobile', 'Mobile Money')], default='virement', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='comptabilite.facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-date'],
            },
        ),
    ]
