# Generated by Django 5.0.6 on 2026-05-08 10:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
        ('crm', '0001_initial'),
        ('projets', '0002_affectationtache_realisationtache_tacheprojet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='fne_balance_sticker',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='facture',
            name='fne_certifiee_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='fne_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='facture',
            name='fne_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='mode_reglement',
            field=models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('check', 'Chèque'), ('mobile-money', 'Mobile Money'), ('transfer', 'Virement'), ('deferred', 'Différé')], default='transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='facture',
            name='template_fne',
            field=models.CharField(choices=[('B2B', 'Entreprise → Entreprise'), ('B2C', 'Entreprise → Particulier'), ('B2G', 'Entreprise → Gouvernement'), ('B2F', 'Entreprise → Financier')], default='B2B', max_length=5),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('vente', 'Vente'), ('avoir', 'Avoir'), ('proforma', 'Proforma')], default='vente', max_length=10),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='fne_item_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='remise_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='taux_tva',
            field=models.CharField(choices=[('TVA', 'TVA normale (18%)'), ('TVAB', 'TVA réduite (9%)'), ('TVAC', 'Exonéré (0%)'), ('TVAD', 'TVA majorée (27%)')], default='TVA', max_length=5),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_emission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('certifiee', 'Certifiée FNE'), ('envoyee', 'Envoyée'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée'), ('en_retard', 'En retard'), ('annulee', 'Annulée')], default='brouillon', max_length=25),
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('expire', 'Expiré')], default='brouillon', max_length=20)),
                ('date_validite', models.DateField()),
                ('remise_globale_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis_comptabilite', to='crm.client')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='comptabilite.devis'),
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(max_length=300)),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remise_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('taux_tva', models.CharField(choices=[('0', 'Exonéré (0%)'), ('9', 'TVA réduite (9%)'), ('18', 'TVA normale (18%)'), ('27', 'TVA majorée (27%)')], default='18', max_length=5)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
            },
        ),
    ]
