# Generated by Django 5.0.6 on 2026-05-17 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_refactoring_sprint2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='numero',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('expire', 'Expiré')], default='brouillon', max_length=15),
        ),
        migrations.AlterField(
            model_name='facture',
            name='devis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture_liee', to='comptabilite.devis'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_reglement',
            field=models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte'), ('check', 'Chèque'), ('mobile-money', 'Mobile Money'), ('transfer', 'Virement'), ('deferred', 'Différé')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero_local',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='template_fne',
            field=models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('B2G', 'B2G'), ('B2F', 'B2F')], default='B2B', max_length=5),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='fne_item_id',
            field=models.CharField(blank=True, help_text='ID ligne renvoyé par FNE — requis pour les avoirs', max_length=100),
        ),
    ]
