# Generated by Django 5.0.6 on 2026-05-21 15:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_devis_facture_liee_related_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('quantite', models.PositiveIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('mobile-money', 'Mobile Money'), ('card', 'Carte bancaire'), ('transfer', 'Virement')], default='mobile-money', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Achat de stickers',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='centre_cout',
            field=models.CharField(blank=True, choices=[('btp', 'BTP'), ('pepiniere', 'Pépinière'), ('location', 'Location'), ('plantation', 'Plantation')], max_length=15),
        ),
        migrations.CreateModel(
            name='StickerMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_mouvement', models.CharField(choices=[('achat', 'Achat / recharge'), ('consommation', 'Consommation'), ('ajustement', 'Ajustement')], max_length=15)),
                ('quantite', models.IntegerField(help_text='Positif (achat) ou négatif (consommation)')),
                ('solde_apres', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='comptabilite.stickerachat')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stickers_mouvements', to='comptabilite.facture')),
            ],
            options={
                'verbose_name': 'Mouvement de stickers',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
