# Generated by Django 5.0.6 on 2026-05-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0005_stickerachat_facture_centre_cout_stickermouvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='facture_origine',
            field=models.ForeignKey(blank=True, help_text="Facture d'origine — renseignée sur les avoirs", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs', to='comptabilite.facture'),
        ),
    ]
