# Generated by Django 5.0.6 on 2026-05-21 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0007_centre_cout_fk'),
        ('core', '0004_seed_centres_cout'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevis',
            name='centre_cout',
            field=models.ForeignKey(blank=True, help_text='Activité de la ligne — devis combinés multi-activités', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_devis', to='core.centrecout'),
        ),
    ]
